[package]
name = "eetf"
version = "0.3.5"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "Library for encoding/decoding Erlang External Term Format"
documentation = "https://docs.rs/eetf"
homepage = "https://github.com/sile/eetf"
repository = "https://github.com/sile/eetf"
readme = "README.md"
keywords = ["erlang"]
license = "MIT"

[dependencies]
num = "0.1"
byteorder = "0.5"
libflate = "0.1"
